package com.cu.hbm.model;
// Generated Jun 21, 2016 7:33:57 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Helado generated by hbm2java
 */
public class Helado implements java.io.Serializable {

	private int idHelado;
	private String sabor;
	private Long precio;
	private Set comprases = new HashSet(0);

	public Helado() {
	}

	public Helado(int idHelado, String sabor) {
		this.idHelado = idHelado;
		this.sabor = sabor;
	}

	public Helado(int idHelado, String sabor, Long precio, Set comprases) {
		this.idHelado = idHelado;
		this.sabor = sabor;
		this.precio = precio;
		this.comprases = comprases;
	}

	public int getIdHelado() {
		return this.idHelado;
	}

	public void setIdHelado(int idHelado) {
		this.idHelado = idHelado;
	}

	public String getSabor() {
		return this.sabor;
	}

	public void setSabor(String sabor) {
		this.sabor = sabor;
	}

	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

}
