package com.cu.hbm.model;
// Generated Jun 21, 2016 7:33:57 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private Set comprases = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(int idUsuario, Set comprases) {
		this.idUsuario = idUsuario;
		this.comprases = comprases;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

}
